### ISSUE TITLE
Spring boot Validation with Oracle DB

### ISSUE THREAD

**Issue by yarabsyp** [bianjp/blog-spring#1]
I have a requirement which need to do a custom validation with bean . The validated metadata can be received from Oracle DB. so based on the DB metadata I want to make bean properties as optional or required, apply patterns and do a cross field validation. Can anyone suggest best practices for these requirements, I want to do all this in spring boot Better if you could share some sample code for reference

Thanks

**Comment by bianjp** [comment]
Out of topic. Ask Google or StackOverflow for help.
